<?php
/**
 * Created by PhpStorm.
 * User: ssj
 * Date: 15-12-31
 * Time: 上午12:07
 */

namespace frontend\controllers;

use Yii;
use yii\filters\auth\QueryParamAuth;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use frontend\models\QueryPeersForm;
use frontend\models\User;

class AnnounceController extends Controller
{
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam' => 'passkey',
        ];
        return $behaviors;
    }
    public function actionQuery()
    {
        Yii::trace(print_r(Yii::$app->request->get()));
        $form = new QueryPeersForm();
        $form->attributes = Yii::$app->request->get();
        Yii::info($form->ip);
        if ($form->validate()) {
            $peer = $form->peer;
            $peer->real_up = $form->uploaded;
            $peer->real_down = $form->downloaded;
            if (intval($form->left) === 0) {
                $peer->status = 'Seeder';
            } else {
                $peer->status = 'Leecher';
            }
            $peer->save();
            //处理event
            switch ($form->event) {
                case 'regular':
                    break;
                case 'started':
                    //do nothing?
                    break;
                case 'stopped':
                    $peer->delete();
                    break;
                case 'completed':
                    $form->seed->completed_count++;
                    $form->seed->save();
                    break;
                default:
                    Yii::warning("Unknown event", static::className());
            }
        } else {
            $errors = $form->errors;
            Yii::warning($errors);
        }
    }
    public function actionError()
    {
    }
}
