<?php
/**
 * Created by PhpStorm.
 * User: ssj
 * Date: 16-1-5
 * Time: 上午7:40
 */

namespace frontend\controllers;

use yii\web\Controller;

class UserController extends Controller
{
    public $enableCsrfValidation = false;
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam' => 'passkey',
        ];
        $behaviors[] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        return $behaviors;
    }

    public function actionInfo()
    {

    }
}
