<?php
/**
 * Created by PhpStorm.
 * User: ssj
 * Date: 16-1-5
 * Time: 上午7:40
 */

namespace frontend\controllers;

use frontend\models\Peer;
use frontend\models\User;
use Yii;
use yii\filters\auth\QueryParamAuth;
use yii\web\Controller;
use yii\web\Response;

class UserController extends Controller
{
    public $enableCsrfValidation = false;
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam' => 'passkey',
        ];
        $behaviors[] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        return $behaviors;
    }

    public function actionInfo($detail = false)
    {
        /** @var User $user */
        $user = User::findOne(Yii::$app->user->identity->getId());
        $ret = $user->attributes;
        if ($detail) {
            $peers = $user->peers;
            $seeder = 0;
            $leecher = 0;
            foreach ($peers as $p) {
                if ($p->status == 'Seeder') {
                    $seeder++;
                } else {
                    $leecher++;
                }
            }
            $ret['seeder'] = $seeder;
            $ret['leecher'] = $leecher;
        }
        return $ret;
    }

}
